os:
- linux
- osx
language: c
sudo: required
services:
- docker
install:
- git submodule update --remote
- bioconda-recipes/scripts/travis-setup.sh
script: travis_wait 50 scripts/travis-run.sh
env:
  global:
  - secure: WS9nwlZfrSgdU5bUw9ZXh5xD067PyUVq+UZnPazORgh5kgkTTX4EsNnXPtmUiQ9DOwVvBiCZzn6c7N+YPuUdEROOR/pBjtFA+w/APFk4ug1tcIzRH7z2we+fZaAnKK3SRqOhHkUYa8tjZFGr53RsaKaxKEc0SIqsHGbDupdBz9KC4raXyUQobcLxWbE6BQq2jhyJGqWxOrhTTrd3WCRKVTgjUlQmwimk6s9txfnEbEguE7UlRhlO0CSqgBj2oUvwtJQSkZWAFminUi2Jcmnduebu42iYX6IF3bYNLVxy8d56v2APGv6reipsD9m3l6URRtpgGygMF4EI9X6dlCjT2qMrwwuWQcZJncFkR584dL+MiPfA2RXamGQybX8HSlnrn60ZKzr5gmw4hetffUGwmOA2VlEW1Wcxcwcef+/8osWwnfLT4I3i736P71LARcBWjBaXKKCXCkCLegv0WB0V/JXyo6IfdLToB0ElAwNfoSlhK1ZtTejngMQewzh6HFcyJwbyPog8/WCL+/j+OohdLZYgiXuldeoLoTwM8YmrSV7twUg3rl2Uc9AWd6iKXC2n8t+2XXdSTwcyrLAEp5J2gZA+HPE/4R6/K1YLbILfMp+u2k8TpazSVX7oRwIcp5UJK6NGx9KDLnT5nJXFW2J5SuBdvQjOXGNSVxyAhBg2AAM=
  - SUBDAGS=20
  matrix:
  - SUBDAG=0
  - SUBDAG=1
  - SUBDAG=2
  - SUBDAG=3
  - SUBDAG=4
  - SUBDAG=5
  - SUBDAG=6
  - SUBDAG=7
  - SUBDAG=8
  - SUBDAG=9
  - SUBDAG=10
  - SUBDAG=11
  - SUBDAG=12
  - SUBDAG=13
  - SUBDAG=14
  - SUBDAG=15
  - SUBDAG=16
  - SUBDAG=17
  - SUBDAG=18
  - SUBDAG=19
